# Generated by Django 5.1.4 on 2025-01-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_post_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='عنوان',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='محتوا',
        ),
    ]
