# Generated by Django 5.1.4 on 2025-01-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_title_post_عنوان_rename_content_post_محتوا'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
